#!/usr/bin/perl
use strict;
use warnings;

# Generate a random number between 1 and 10
my $secret_number = int(rand(10)) + 1;
my $guess;
my $attempts = 0;

print "Welcome to the Perl Number Guessing Game!\n";

while (1) {
    print "Guess a number between 1 and 10: ";
    $guess = <STDIN>;
    chomp($guess);
    $attempts++;

    # Check if the input is a number
    if ($guess !~ /^\d+$/) {
        print "Please enter a valid number.\n";
        next;
    }

    if ($guess == $secret_number) {
        print "🎉 Correct! You guessed it in $attempts tries.\n";
        last;
    } elsif ($guess < $secret_number) {
        print "Too low. Try again.\n";
    } else {
        print "Too high. Try again.\n";
    }
}
